name: NodeJS CI

on: 
  - push
  - pull_request

jobs:
  Linter_verification:
    name: Linter verification
    runs-on: ubuntu-latest
  
    steps:
       - name: Check out repository
         uses: actions/checkout@v2
       - name: Check Eslint
         run: make lint
    
  
  
