name: NodeJS CI

on: 
  - push
  - pull_request

jobs:
  Linter_verification:
    name: Linter verification
    runs-on: ubuntu-latest
  
    steps:
       - name: Check out repository
         uses: actions/checkout@v2
       - name: Use Node.js
         uses: actions/setup-node@v1
         with:
              node-version: '16.x'
       - name: npm install
         run: make install 
       - name: Check Eslint
         run: make lint
    
  
  
